# name: Check Swim Spaces

# on:
#   schedule:
#     - cron: "*/30 * * * *" # every 30 minutes
#   workflow_dispatch: # allow manual run

# jobs:
#   check:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       - name: Run checker
#         env:
#           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#         run: |
#           sed -i "s/YOUR_BOT_TOKEN/$TELEGRAM_BOT_TOKEN/" config.json
#           sed -i "s/YOUR_CHAT_ID/$TELEGRAM_CHAT_ID/" config.json
#           python main.py
